# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAZ7NcsNWwZdu7_7ALWkgC1CdFUbsC_D
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from scipy.ndimage import gaussian_filter

# ==========================================
# CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(page_title="Tablero Handball Live", layout="wide")
st.title("📊 Análisis Táctico en Vivo - Selección Nacional Femenil")

# Imágenes requeridas en la misma carpeta que el script
IMAGEN_PORTERIA = 'NS_Goal_handball.png'
IMAGEN_CANCHA = 'NS_ui_Balonmano_BL_V_T.jpg'
COLOR_LOC = 'green'
COLOR_VIS = 'blue'

# ==========================================
# 1. CONEXIÓN A DATOS (Actualización cada 5s)
# ==========================================
@st.cache_data(ttl=5)
def load_data():
    # Aquí irá tu pd.read_csv("LINK_DE_GOOGLE_SHEETS")
    # Por ahora, usamos datos simulados idénticos a los del iPad para que veas que funciona
    data = pd.DataFrame({
        'Equipo': ['LOC', 'LOC', 'VIS', 'LOC', 'VIS', 'VIS'],
        'Fase': ['Posicional', 'Transicion', 'Posicional', 'Posicional', 'Transicion', 'Penal'],
        'Resultado': ['Gol', 'Gol', 'Parada', 'Fallo', 'Gol', 'Gol'],
        'Tiempo': ['01:15.00', '03:45.50', '05:10.20', '08:30.00', '10:05.10', '12:00.00'],
        'Periodo': ['1T', '1T', '1T', '1T', '1T', '1T'],
        'Coord Lado': ['50,80', '80,20', '25,75', '45,90', '10,10', '50,50'],
        'Coord Porteria': ['15,85', '80,20', '50,50', '', '90,10', '20,80']
    })
    return data

df_vivo = load_data()

# ==========================================
# 2. FILTROS INTERACTIVOS
# ==========================================
st.sidebar.image(IMAGEN_CANCHA, use_column_width=True) # Logo / Decoración
st.sidebar.header("Filtros del Partido")
equipo_sel = st.sidebar.selectbox("Selecciona Equipo", ['Todos'] + list(df_vivo['Equipo'].unique()))
fase_sel = st.sidebar.selectbox("Fase de Juego", ['Todas', 'Posicional', 'Transicion', 'Penal'])

# Aplicar filtros
df = df_vivo.copy()
if equipo_sel != 'Todos':
    df = df[df['Equipo'] == equipo_sel]
if fase_sel != 'Todas':
    df = df[df['Fase'] == fase_sel]

# ==========================================
# 3. MÉTRICAS RÁPIDAS
# ==========================================
col1, col2, col3, col4 = st.columns(4)
col1.metric("Goles", len(df[df['Resultado'] == 'Gol']))
col2.metric("Paradas", len(df[df['Resultado'] == 'Parada']))
col3.metric("Fallos", len(df[df['Resultado'] == 'Fallo']))
col4.metric("Pérdidas", len(df[df['Resultado'] == 'Perdida']))

st.divider()

# ==========================================
# 4. FUNCIONES DE DIBUJO (Extraídas de tu Colab)
# ==========================================

def plot_cancha(df_filtrado, equipo_nombre):
    fig, ax = plt.subplots(figsize=(6, 10))
    try:
        img = mpimg.imread(IMAGEN_CANCHA)
        ax.imshow(img, extent=[0, 100, 100, 0])
    except FileNotFoundError:
        ax.text(50, 50, "Imagen de Cancha no encontrada", color="white", ha='center')
        ax.set_facecolor('black')

    # Extraer coordenadas[cite: 2]
    def extraer_coord(val, indice):
        try: return float(str(val).split(',')[indice])
        except: return np.nan

    df_filtrado = df_filtrado.copy()
    df_filtrado['PX'] = df_filtrado['Coord Lado'].apply(lambda x: extraer_coord(x, 0))
    df_filtrado['PY'] = df_filtrado['Coord Lado'].apply(lambda x: extraer_coord(x, 1))
    df_cancha = df_filtrado.dropna(subset=['PX', 'PY'])

    if len(df_cancha) > 0:
        heatmap, xedges, yedges = np.histogram2d(df_cancha['PX'], df_cancha['PY'], bins=100, range=[[0, 100], [0, 100]])
        heatmap = heatmap.T
        heatmap_suave = gaussian_filter(heatmap, sigma=4)
        ax.imshow(heatmap_suave, extent=[0, 100, 100, 0], cmap='inferno', alpha=0.55)

        goles = df_cancha[df_cancha['Resultado'] == 'Gol']
        no_goles = df_cancha[df_cancha['Resultado'] != 'Gol']

        ax.scatter(no_goles['PX'], no_goles['PY'], c='white', marker='X', s=100, alpha=0.9, edgecolors='black', label='No Gol')
        ax.scatter(goles['PX'], goles['PY'], c='#00e676', s=120, edgecolors='black', linewidth=1.5, label='Gol')
        ax.legend(loc='upper right', fontsize=10)

    ax.set_title(f'Mapa de Ataque', fontweight='bold', fontsize=14, pad=15)
    ax.axis('off')
    return fig

def plot_porteria(df_filtrado):
    fig, ax = plt.subplots(figsize=(10, 5))
    try:
        img = mpimg.imread(IMAGEN_PORTERIA)
        ax.imshow(img, extent=[0, 100, 100, 0])
    except FileNotFoundError:
        ax.text(50, 50, "Imagen Portería no encontrada", color="white", ha='center')
        ax.set_facecolor('gray')

    # Procesar coordenadas de portería[cite: 2]
    df_tiros = df_filtrado[df_filtrado['Coord Porteria'].notna() & (df_filtrado['Coord Porteria'] != '')].copy()

    if len(df_tiros) > 0:
        df_tiros['PX'] = df_tiros['Coord Porteria'].apply(lambda x: float(str(x).split(',')[0]) if ',' in str(x) else np.nan)
        df_tiros['PY'] = df_tiros['Coord Porteria'].apply(lambda x: float(str(x).split(',')[1]) if ',' in str(x) else np.nan)
        goles = df_tiros[df_tiros['Resultado'] == 'Gol']

        if len(goles) > 0:
            heatmap, xedges, yedges = np.histogram2d(goles['PX'], goles['PY'], bins=100, range=[[0, 100], [0, 100]])
            heatmap = heatmap.T
            heatmap_suave = gaussian_filter(heatmap, sigma=5)

            if np.max(heatmap_suave) > 0:
                heatmap_suave = heatmap_suave / np.max(heatmap_suave)
            heatmap_suave[heatmap_suave < 0.05] = np.nan
            ax.imshow(heatmap_suave, extent=[0, 100, 100, 0], cmap='inferno', alpha=0.65)

    ax.set_title('Vulnerabilidad en Portería (Goles)', fontweight='bold', fontsize=14, pad=15)
    ax.set_xlim(0, 100)
    ax.set_ylim(100, 0)
    ax.axis('off')
    return fig

# ==========================================
# 5. RENDERIZADO DE GRÁFICAS EN COLUMNAS
# ==========================================
col_izq, col_der = st.columns(2)

with col_izq:
    st.markdown("### 🏟️ Origen de la Acción")
    fig_cancha = plot_cancha(df, equipo_sel)
    st.pyplot(fig_cancha)

with col_der:
    st.markdown("### 🥅 Zonas de Definición")
    fig_porteria = plot_porteria(df)
    st.pyplot(fig_porteria)

# ==========================================
# 6. TABLA DE DATOS CRUDOS
# ==========================================
with st.expander("Ver Base de Datos Cruda"):
    st.dataframe(df)